export const INITIAL_ITEMS = [
  { id: "1", name: "TOMATO", hindiName: "टमाटर", quantity: 0, rate: 0 },
  { id: "2", name: "CABBAGE", hindiName: "पत्तागोभी", quantity: 0, rate: 0 },
  { id: "3", name: "FRENCH BEANS", hindiName: "फ्रेंच बीन्स", quantity: 0, rate: 0 },
  { id: "4", name: "CARROT", hindiName: "गाजर", quantity: 0, rate: 0 },
  { id: "5", name: "CUCUMBER", hindiName: "खीरा", quantity: 0, rate: 0 },
  { id: "6", name: "BEET ROUT", hindiName: "चुकंदर", quantity: 0, rate: 0 },
  { id: "7", name: "GINGER", hindiName: "अदरक", quantity: 0, rate: 0 },
  { id: "8", name: "GREEN CHILIES", hindiName: "हरी मिर्च", quantity: 0, rate: 0 },
  { id: "9", name: "CAPSICUM", hindiName: "शिमला मिर्च", quantity: 0, rate: 0 },
  { id: "10", name: "RADISH", hindiName: "मूली", quantity: 0, rate: 0 },
  { id: "11", name: "CELERY", hindiName: "सेलरी", quantity: 0, rate: 0 },
  { id: "12", name: "LEMON", hindiName: "नींबू", quantity: 0, rate: 0 },
  { id: "13", name: "SPINCH", hindiName: "पालक", quantity: 0, rate: 0 },
  { id: "14", name: "MINT", hindiName: "पुदीना", quantity: 0, rate: 0 },
  { id: "15", name: "CORINDER", hindiName: "धनिया", quantity: 0, rate: 0 },
  { id: "16", name: "SPRING ONION", hindiName: "हरा प्याज़", quantity: 0, rate: 0 },
  { id: "17", name: "CARRY LEAVES", hindiName: "कड़ी पत्ता", quantity: 0, rate: 0 },
  { id: "18", name: "BIG POTATO", hindiName: "बड़ा आलू", quantity: 0, rate: 0 },
  { id: "19", name: "ONION", hindiName: "प्याज़", quantity: 0, rate: 0 },
  { id: "20", name: "GARLIC", hindiName: "लहसुन", quantity: 0, rate: 0 },
  { id: "21", name: "LADY FINGERS", hindiName: "भिंडी", quantity: 0, rate: 0 },
  { id: "22", name: "BRINJAL", hindiName: "बैंगन", quantity: 0, rate: 0 },
  { id: "23", name: "PUMPKIN", hindiName: "कद्दू", quantity: 0, rate: 0 },
  { id: "24", name: "MASHROOM", hindiName: "मशरूम", quantity: 0, rate: 0 },
  { id: "25", name: "BROCCOLI", hindiName: "ब्रोकोली", quantity: 0, rate: 0 },
  { id: "26", name: "RED/YELLOW CAPSICUM", hindiName: "लाल/पीली शिमला मिर्च", quantity: 0, rate: 0 },
  { id: "27", name: "AMERECION BABYCON", hindiName: "अमेरिकन बेबी कॉर्न", quantity: 0, rate: 0 },
  { id: "28", name: "CAUULI FLOWER", hindiName: "फूलगोभी", quantity: 0, rate: 0 },
  { id: "29", name: "SHENG", hindiName: "सहजन (ड्रमस्टिक)", quantity: 0, rate: 0 },
  { id: "30", name: "SHURAN", hindiName: "सूरन (जिमीकंद)", quantity: 0, rate: 0 },
];
